Repository AspectOS/aspectos.github.io, pull requests merged in 2022-04, with the labels that each got.

#38 Pretty Footer and Navbar, Plus Some Formatting Fixes
  403.html
  about/index.html
  docs/index.html
  downloads/index.html
  dummy.html
  images/PrettyBackgroundImage.jpg
  index.html
  main.css
Labels: low priority, appearance, bugfix

#43 Dark Mode Addons
  403.html
  about/index.html
  docs/index.html
  downloads/index.html
  dummy.html
  images/PrettyBackgroundImageDark.jpg
  index.html
  main.css
Labels: enhancement, medium priority, appearance, bugfix

#42 [bugfix][apperance]Patch index.html
  index.html
Labels: medium priority, appearance, bugfix

#49 [bugfix][apperance] Patch 403.html
  403.html
Labels: low priority, appearance, bugfix

#50 [bugfix][apperance] Patch 404.html
  404.html
Labels: low priority, appearance, bugfix

#52 [bugfix][apperance] Patch dummy.html
  dummy.html
Labels: low priority, appearance, bugfix

#46 [feature] Major Update which includes Dark Mode Toggle.
  403.html
  404.html
  about/index.html
  docs/index.html
  downloads/index.html
  dummy.html
  index.html
  main.css
  script.js
Labels: enhancement
